export const events = [
  { 
    nameOfEvent: 'meet with friends',
    data: new Date(2020, 1, 25),
    startEvent: '12:00',
    endEvent: '14:00',
    color: null,
    id: null,
  },
  { 
    nameOfEvent: 'go to football',
    data: new Date(2020, 1, 25),
    startEvent: '13:00',
    endEvent: '14:45',
    color: null,
    id: null,
  },
  { 
    nameOfEvent: 'buy something',
    data: new Date(2020, 1, 18),
    startEvent: '14:00',
    endEvent: '15:00',
    color: null,
    id: null,
  },
  { 
    nameOfEvent: 'go to hospital',
    data: new Date(2020, 1, 22),
    startEvent: '15:30',
    endEvent: '16:00',
    color: null,
    id: null,
  },
  { 
    nameOfEvent: 'skype with mentor',
    data: new Date(2020, 1, 26),
    startEvent: '20:45',
    endEvent: '21:15',
    color: null,
    id: null,
  },
  { 
    nameOfEvent: 'english lesson',
    data: new Date(2020, 1, 26),
    startEvent: '22:45',
    endEvent: '23:00',
    color: null,
    id: null,
  },
  { 
    nameOfEvent: 'event fake',
    data: new Date(2020, 1, 26),
    startEvent: '10:45',
    endEvent: '10:00',
    color: null,
    id: null,
  },
  { 
    nameOfEvent: 'event fake2',
    data: new Date(2020, 1, 26),
    startEvent: '19:15',
    endEvent: '18:00',
    color: null,
    id: null,
  },
];